import os
import sys
from typing import Tuple

import numpy as np

# Add project root and shared utilities to Python's import path.
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
for _p in (_ROOT, os.path.join(_ROOT, "src", "common")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import config
import io_utils
import m3_preprocess


def detect_presence(crop_bgr: np.ndarray) -> Tuple[bool, str]:
    # Use the configured ink-ratio threshold to distinguish signatures from blank cells.
    if m3_preprocess.ink_ratio(crop_bgr) < config.INK_PIXEL_RATIO_THRESHOLD:
        return False, "blank"
    return True, "signature"


def detect_file(crop_path) -> Tuple[bool, str]:
    # Load the cropped image and pass it to the signature detector.
    return detect_presence(io_utils.load_bgr(crop_path))


def detect_all():
    # Locate the student signature crops generated by the previous processing stage.
    crops_root = config.OUTPUT_DIR / "crops"
    if not crops_root.exists():
        print("No crops. Run: python src/m2_crop.py first.")
        return {}

    results = {}

    # Process each sheet and check the expected six attendance rows.
    for sheet_dir in sorted(p for p in crops_root.iterdir() if p.is_dir()):
        rows = []

        for row in range(1, 7):
            f = sheet_dir / f"row_{row}.png"
            if not f.exists():
                continue

            present, reason = detect_file(f)
            results[(sheet_dir.name, row)] = (present, reason)

            # P indicates a detected signature; A indicates a blank cell.
            mark = "P" if present else "A"
            rows.append(f"{row}:{mark}({reason})")

        print(f"[M4] {sheet_dir.name:24s} {'  '.join(rows)}")

    return results


if __name__ == "__main__":
    detect_all()